### ISSUE TITLE
Improve DNS verification for CNAME check

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/external-domain-broker#237]
In order to make dns resolver more robust, we want to add additional [`DNS_VERIFICATION_SERVERS`](https://github.com/cloud-gov/external-domain-broker/blob/fcbebb6cda46445e13ab176c3d7d1ecd5b5496ab/broker/config.py#L79) and check other severs if the [dns resolver](https://github.com/cloud-gov/external-domain-broker/blob/fcbebb6cda46445e13ab176c3d7d1ecd5b5496ab/broker/dns.py#L7) fails. Certain customer name servers may to longer to propagate across other verification servers and lead to failures when creating the external domain service.

## Acceptance Criteria
* [ ] Add additional DNS verification servers to the config
* [ ] Given dns [get_cname](https://github.com/cloud-gov/external-domain-broker/blob/fcbebb6cda46445e13ab176c3d7d1ecd5b5496ab/broker/dns.py#L12), resolve against multiple verification servers if the previous one fails to resolve the cname.

--- 

## Security considerations
none

**Comment by bengerman13** [comment]
it would be ideal if we could match the logic Lets Encrypt does, but they do that using their own resolution logic.

Short of that, I _think_ adding more servers is likely going to be playing whack-a-mole

**Comment by bengerman13** [comment]
I think it'd make sense to see how hard it would be to use the LE logic first. If it's possible/plausible, use that. If it's not, then maybe track how often this happens.

**Comment by bengerman13** [comment]
this is the server Lets Encrypt uses: https://nlnetlabs.nl/projects/unbound/about/

**Comment by markdboyd** [comment]
@apburnes Has this continued to be an issue for Pages? Trying to gauge the value in keeping this ticket open

**Comment by markdboyd** [comment]
Confirmed with @apburnes that we have not seen this issue in some time. Closing.
