### ISSUE TITLE
Update boto3 version to currnet

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/external-domain-broker#283]
AWS is alerting cloud.gov that we are using deprecated versions of boto3 health SDK and need to above versions `1.27.1`  to work.  As of Feb'24 version `1.34.34` is the most recent version.

## Notes

- Validate that recent versions don't introduce new issues/bugs

## Acceptance Criteria

- [ ] Determine code changes needed for the upgrade
- [ ] Throughly test in lower environments
- [ ] If a test suite does not exist in the repo - create on to validate new versions of `boto3` in the future

**Comment by markdboyd** [comment]
This change has been deployed to production and successfully passed the acceptance tests there
