### ISSUE TITLE
During update to domain plan - old DNS records are not removed

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/external-domain-broker#291]
Plan: domain
Action: update-service to reduce the number of domains
Result: new cert is created and elb and DNS records for remaining domains are updated but removed domain DNS records for `_acme-challenge` and `<domain>` on the `external-domains->env>` domain are not removed 

## Test notes

- pushed a test ruby hello world
- Using the [cloud-gov-test-domain-3.com](http://cloud-gov-test-domain-3.com/) domain in commercial route 53 I created the needed _acme-challenge. and name records using the published CNAME instructions
- cf create-service external-domain domain my-domain -c '{"domains": "[pickles.cloud-gov-test-domain-3.com](http://pickles.cloud-gov-test-domain-3.com/),[mustard.cloud-gov-test-domain-3.com](http://mustard.cloud-gov-test-domain-3.com/)"}'
- After a few minutes I seen the _acme-challenge records on the [external-domains-production.cloud.gov](http://external-domains-production.cloud.gov/) hosted zone and then the CNAME records for the domain instance on production-domains3
- Added the domains to the org and mapped my routes
- Tested and pickles was the cert subject and pickles and mustard where both listed on SAN

- `cf update-service my-domain -c '{"domains": "[pickles.cloud-gov-test-domain-3.com](http://pickles.cloud-gov-test-domain-3.com/)"}'`
- I see the pickles record moved from production-domains-3 to production-domains-2.
- The old cert is now gone off production-domains-3
- pickles works and only has the subject

- Noticed the `_acme-challenge` and `<domain>.external-domains-<env>.cloud.gov` records for the removed domain still exist.  If someone goes to `<domain>.external-domains-<env>.cloud.gov` they will get the default `*.fr.cloud.gov` cert from that elb instead of a DNS failure as expected if the records are removed

## Acceptance Criteria

- [ ] Update logic on update to plans where a domain(s) are removed.

**Comment by bengerman13** [comment]
I'm like 90% sure that if this is happening for the `domain` plan, it's also happening for `domain-with-cdn`

**Comment by markdboyd** [comment]
Confirmed this is fixed by following the manual testing steps in the ticket description
