### ISSUE TITLE
Notify customers of impending deprecation

### ISSUE THREAD

**Issue by tammersaleh** [cloud-gov/external-domain-broker#34]
We need to let users know that the existing domain broker will no longer be able to provision new instances in 40 days.  Because our deprecation policy is 30 days, we need to send this as soon as possible.

All existing instances will continue to work fine until June 2021.  We're working on a replacement and plan to have it in place before the current broker stops working.  We don't have a migration strategy yet for existing instances.

References:
- [Let's Encrypt Google Calendar](https://calendar.google.com/calendar/embed?src=letsencrypt.org_caqskun93lgiabjj4ba9cb1rek%40group.calendar.google.com) showing new cert EOL on June 1
- [Deprecation notice](https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430) describing overall timeline
- The replacement broker is being developed at [cloud-gov/domain-broker](https://github.com/cloud-gov/domain-broker)

**Comment by tammersaleh** [comment]
@karareinsel This is ready for you to throw on whichever board you like.

**Comment by karareinsel** [comment]
Text for email communication and StatusPage update.
https://docs.google.com/document/d/1Nl3RX6FrdXBRRAX6q1EbIgXB7jeo5qc_p3Rm7UMKp9o/edit
