### ISSUE TITLE
Task monitoring

### ISSUE THREAD

**Issue by tammersaleh** [cloud-gov/external-domain-broker#39]
Alerts on:

- task failure to detect bugs and downstream issues (required for launch)
- task queue depth to detect down workers (good to have)
- task duration? (not even sure)

**Comment by tammersaleh** [comment]
For alerting on task failure: https://huey.readthedocs.io/en/latest/api.html#Task.error

**Comment by markdboyd** [comment]
This ticket is quite old and stale. Closing for now and we can reopen if necessary
