### ISSUE TITLE
Customer documentation on cloud.gov

### ISSUE THREAD

**Issue by tammersaleh** [cloud-gov/external-domain-broker#63]
- [ ] add a new page for the External Domain Service
- [ ] Deprecate https://cloud.gov/docs/services/cdn-route/ and https://cloud.gov/docs/services/custom-domains/

**Comment by mheadd** [comment]
Happy to pitch in an help on these doc updates if needed, @tammersaleh

**Comment by tammersaleh** [comment]
Hey @mheadd  - have you had a chance to get started on this?

**Comment by mheadd** [comment]
@tammersaleh Yup, I have a PR for the cloud.gov docs stubbed out here: https://github.com/cloud-gov/cg-site/pull/1698
