### ISSUE TITLE
Schedule maintenance windows

### ISSUE THREAD

**Issue by tammersaleh** [cloud-gov/external-domain-broker#65]
The CDN and Custom Domain services will both have outages on [the dates in this calendar](https://calendar.google.com/calendar/embed?src=letsencrypt.org_caqskun93lgiabjj4ba9cb1rek%40group.calendar.google.com).  We need to create statuspage maintenance windows for them.

**Comment by tammersaleh** [comment]
Maybe link to this status page update for context: https://cloudgov.statuspage.io/incidents/gxl7h0pgkp6r

**Comment by ccostino** [comment]
@tammersaleh, this means creating maintenance windows for each of the dates listed between June 1st and July 2nd on this calendar for all of the V1 validations being disabled temporarily and then permanently, correct?

Is there any specific messaging you had in mind?  If not, I can draft something and post it here for review before sending each of them off.

**Comment by tammersaleh** [comment]
yeah, that's correct.  maybe work with Kara on messaging?

**Comment by ccostino** [comment]
[The draft is (will be) here](https://docs.google.com/document/d/1oc3upRGGK_iaNplfd1i-r1JA4ImKGpfwJDzEEu6PdvI/edit#).

**Comment by ccostino** [comment]
@tammersaleh, can you please take a look at the [draft message](https://docs.google.com/document/d/1oc3upRGGK_iaNplfd1i-r1JA4ImKGpfwJDzEEu6PdvI/edit#heading=h.czx4cc7f9fx9) we have written up to make sure it covers the pertinent details?

Our plan is to schedule maintenance notices for each of these dates with this message, including July 2nd.  Please feel free to make any modifications directly if they're needed.  Thanks!

**Comment by karareinsel** [comment]
@eddietejeda and @mheadd are also reviewing the messaging and editing/offering feedback.

**Comment by ccostino** [comment]
Thank you!

**Comment by ccostino** [comment]
Thank you all for the reviews!  Drafts were finalized and the maintenance notices were scheduled and sent out in StatusPage this morning.
